// theme.js
// Central theme config for UI colors and palette

export const UI_THEME = {
    bg: '#f1faee',
    border: '#1e3231',
    header: '#1e3231',
    sectionBg: '#e0e4e2',
    sectionBorder: '#6e9075',
    headerBorder: '#6e9075',
    labelBg: '#f8f8f3',
    labelText: '#3d5a6c',
    sliderThumb: '#bcb6c6',
    sliderThumbBorder: '#3d5a6c',
    sliderTrack: '#e0e4e2',
    sliderTrackBorder: '#bfcad6',
    sliderFocus: '#bcb6c6',
    sliderDisabled: '#dbe3e6',
    toggleBg: '#b7b7a4',
    toggleColor: '#3d3d2d',
    toggleHover: '#bc6c25',
    capacityBg: '#f1faee',
    capacityBorder: '#2d6a4f',
    capacityText: '#2d6a4f',
    headerTitle: '#1e3231',
    sectionTitle: '#3d3d4c',
    scrollbarThumb: '#6e9075',
    scrollbarThumbHover: '#5a735f',
    scrollbarTrack: '#e0e4e2',
};
